[package]
name = "rustwave"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.34", features = ["cargo"] }
futures = "0.3.31"
reqwest = "0.12.15"
tokio = { version = "1.44.1", features = ["full"] }
